services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase
    depends_on:
      - mongo
    volumes:
      - .:/app
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
